va`r Game_List = "[/n " + [
	'{"name" : "Final Fantasy", "Genre" : "RolePlaying", "Main Character" : "Light Warriors", "Year Released" : "1987", "Main Bad Guy" : " "}',
	'{"name" : "Final Fantasy II", "Genre" : "RolePlaying", "Main Character" : "Firion", Year Released" : "1988", "Main Bad Guy" : " "}',
	'{"name" : "Final Fantasy III", "Genre" : "RolePlaying", "Main Character" : "The Four Orphans", "Year Released" : "1990", "Main Bad Guy" : " "}', 
	'{"name" : "Final Fantasy IV", "Genre" : "RolePlaying", "Main Character" : "Cecil Harvey", "Year Released" : "1991", "Main Bad Guy" : " "}',
	'{"name" : "Final Fantasy V", "Genre" : "RolePlaying", "Main Character" : "Bartz Klauser", "Year Released" : "1992", "Main Bad Guy" : " "}',
	'{"name" : "Final Fantasy VI", "Genre" : "RolePlaying", "Main Character" : "Terra Branford", "Year Released" : "1994", "Main Bad Guy" : " "}',
	'{"name" : "Final Fantasy VII", "Genre" : "RolePlaying", "Main Character" : "Cloud Strife", "Year Released" : "1997", "Main Bad Guy" : " "}',
	'{"name" : "Final Fantasy VIII", "Genre" : "RolePlaying", "Main Character" : "Squall Leonhard", "Year Released" : "1999", "Main Bad Guy" : " "}',
	'{"name" : "Final Fantasy IX", "Genre" : "RolePlaying", "Main Character" : "Zidane Tribal", "Year Released" : "2000", "Main Bad Guy" : " "}',
	'{"name" : "Final Fantasy X", "Genre" : "RolePlaying", "Main Character" : "Tidus", "Year Released" : "2001", "Main Bad Guy" : " "}',
	'{"name" : "Final Fantasy X-2", "Genre" : "RolePlaying", "Main Character" : "Yuna", "Year Released" : "2003", "Main Bad Guy" : " "}',
	'{"name" : "Final Fantasy XII", "Genre" : "RolePlaying", "Main Character" : "Vaan", "Year Released" : "2006", "Main Bad Guy" : " "}',
	'{"name" : "Final Fantasy XIII", "Genre" : "RolePlaying", "Main Character" : "Lightning Farron", "Year Released" : "2009", "Main Bad Guy" : " "}',
	'{"name" : "Final Fantasy XIII-2", "Genre" : "RolePlaying", "Main Character" : "Sarah Farron and Noel Kreiss", "Year Released" : "2013", "Main Bad Guy" : " "}',
	'{"name" : "Final Fantasy XIII: Lightning Returns", "Genre" : "RolePlaying", "Main Character" : "Lightning Farron", "Year Released" : "2014", "Main Bad Guy" : " "}',
